import { db } from "@workspace/db";
import { libraryBooksTable } from "@workspace/db/schema";

const books = [
  {
    title: "Data Structures and Algorithms in Python",
    author: "Michael T. Goodrich",
    category: "coding",
    coverUrl: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=300&h=420&fit=crop",
    shortDesc: "A comprehensive guide to DSA using Python with real-world examples and exercises.",
    description: "Master data structures and algorithms through Python implementations. This book covers arrays, linked lists, trees, graphs, sorting, searching, dynamic programming, and more — with clear explanations and Python code that you can run immediately. Ideal for students preparing for coding interviews or wanting to strengthen their CS fundamentals.",
    aiSummary: "This book teaches fundamental data structures (arrays, stacks, queues, trees, graphs, hash maps) and algorithms (sorting, searching, dynamic programming, greedy algorithms) using Python. Key takeaways: 1) Always analyze time and space complexity using Big-O notation. 2) Choose the right data structure for each problem. 3) Recursion and dynamic programming solve complex problems by breaking them into subproblems. 4) Graphs model real-world relationships and are solved with BFS/DFS. Practice consistently on platforms like LeetCode.",
    contentPreview: "Chapter 1: Arrays and Sequences\n\nAn array is a contiguous block of memory storing elements of the same type. Python's list is a dynamic array that grows automatically.\n\nKey operations:\n- Access: O(1) — Direct index access\n- Search: O(n) — Linear scan\n- Insert/Delete at end: O(1) amortized\n- Insert/Delete at middle: O(n)\n\nExample:\n```python\n# Two Sum - find two numbers that add to target\ndef two_sum(nums, target):\n    seen = {}\n    for i, num in enumerate(nums):\n        complement = target - num\n        if complement in seen:\n            return [seen[complement], i]\n        seen[num] = i\n    return []\n```\nTime: O(n), Space: O(n)",
    tags: ["python", "dsa", "algorithms", "interview-prep", "coding"],
    pages: 748,
    readingTimeMinutes: 1200,
    isFree: true,
    priceCredits: 0,
    rating: "4.87",
    reviewCount: 2341,
    downloads: 18920,
  },
  {
    title: "Clean Code: A Handbook of Agile Software Craftsmanship",
    author: "Robert C. Martin",
    category: "coding",
    coverUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=300&h=420&fit=crop",
    shortDesc: "Learn to write readable, maintainable, and professional-grade code.",
    description: "Clean Code is a must-read for every developer. Robert Martin explains the principles of writing code that is easy to understand, maintain, and extend. Learn about meaningful naming, small functions, error handling, unit testing, and refactoring techniques that separate good programmers from great ones.",
    aiSummary: "Clean Code teaches software craftsmanship. Core principles: 1) Names should reveal intent — avoid abbreviations. 2) Functions should do ONE thing and be small. 3) Avoid comments — write self-documenting code instead. 4) Error handling should not obscure logic. 5) Write tests first (TDD). 6) Classes should have single responsibility. 7) Refactor continuously. The boy scout rule: 'Leave the code cleaner than you found it.'",
    contentPreview: "Chapter 2: Meaningful Names\n\nThe name of a variable, function, or class should answer why it exists, what it does, and how it is used. If a name requires a comment, then the name does not reveal its intent.\n\nBad:\n```python\nd = 18  # elapsed time in days\n```\n\nGood:\n```python\nelapsed_time_in_days = 18\n```\n\nAvoid disinformation. Don't name a list of accounts accountList unless it's actually a List type. Use pronounceable names — genymdhms vs generationTimestamp.",
    tags: ["software-engineering", "best-practices", "refactoring", "coding"],
    pages: 431,
    readingTimeMinutes: 600,
    isFree: false,
    priceCredits: 120,
    rating: "4.92",
    reviewCount: 5821,
    downloads: 34210,
  },
  {
    title: "Physics for Class 12 — CBSE Complete Guide",
    author: "H.C. Verma",
    category: "school",
    coverUrl: "https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=300&h=420&fit=crop",
    shortDesc: "Complete CBSE Class 12 Physics with solved problems, derivations, and PYQs.",
    description: "Comprehensive coverage of all Class 12 Physics chapters as per the CBSE syllabus. Includes Electrostatics, Current Electricity, Magnetism, Electromagnetic Induction, Optics, Dual Nature of Radiation, Atoms, Nuclei, and Electronic Devices. Each chapter has theory, solved examples, NCERT solutions, and previous year questions.",
    aiSummary: "Class 12 Physics key concepts: 1) Electrostatics — Coulomb's Law, Electric Field, Gauss's Law, capacitors. 2) Current Electricity — Ohm's Law, Kirchhoff's Laws, Wheatstone bridge. 3) Magnetism — Biot-Savart Law, Ampere's Law, electromagnetic induction (Faraday/Lenz). 4) Optics — Refraction, lenses, mirrors, Young's double slit. 5) Modern Physics — Photoelectric effect, Bohr's model, nuclear physics. Focus on derivations and numerical problems for board exams.",
    contentPreview: "Chapter 1: Electric Charges and Fields\n\n1.1 Electric Charge\nCharge is the fundamental property of matter. Two types: positive (protons) and negative (electrons).\n\nCoulomb's Law:\nF = kq₁q₂/r²\nwhere k = 9 × 10⁹ Nm²C⁻²\n\nKey points:\n• Charge is conserved — total charge of an isolated system remains constant\n• Charge is quantized — q = ne, where e = 1.6 × 10⁻¹⁹ C\n• Like charges repel, unlike charges attract\n\nSolved Example:\nTwo charges of +3μC and -5μC are 10cm apart. Find the force.\nF = (9×10⁹ × 3×10⁻⁶ × 5×10⁻⁶) / (0.1)² = 13.5 N (attractive)",
    tags: ["physics", "class-12", "cbse", "electrostatics", "board-exam"],
    pages: 512,
    readingTimeMinutes: 900,
    isFree: true,
    priceCredits: 0,
    rating: "4.79",
    reviewCount: 8932,
    downloads: 52100,
  },
  {
    title: "Machine Learning with Python — From Zero to Production",
    author: "Aurélien Géron",
    category: "ai-ml",
    coverUrl: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=300&h=420&fit=crop",
    shortDesc: "Build and deploy ML models using scikit-learn, TensorFlow, and Keras.",
    description: "A practical guide to machine learning covering supervised learning, unsupervised learning, neural networks, and deep learning. Build real projects including image classifiers, text analyzers, and recommendation systems. Learn how to preprocess data, train models, evaluate performance, and deploy to production.",
    aiSummary: "ML fundamentals: 1) Supervised Learning — labeled data, regression (predict numbers) and classification (predict categories). 2) Key algorithms: Linear Regression, Logistic Regression, Decision Trees, Random Forests, SVMs, Neural Networks. 3) Training pipeline: Data collection → Preprocessing → Feature engineering → Model training → Evaluation → Deployment. 4) Avoid overfitting with cross-validation and regularization. 5) Deep Learning: CNNs for images, RNNs/Transformers for text. Use scikit-learn for classical ML, TensorFlow/PyTorch for deep learning.",
    contentPreview: "Chapter 3: Classification\n\nA classifier predicts which category an instance belongs to.\n\n```python\nfrom sklearn.datasets import load_digits\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import cross_val_score\n\ndigits = load_digits()\nX, y = digits.data, digits.target\n\nclf = RandomForestClassifier(n_estimators=100, random_state=42)\nscores = cross_val_score(clf, X, y, cv=5, scoring='accuracy')\nprint(f'Accuracy: {scores.mean():.3f} ± {scores.std():.3f}')\n# Output: Accuracy: 0.971 ± 0.008\n```\n\nKey metrics:\n- Accuracy: correct predictions / total\n- Precision: TP / (TP + FP)\n- Recall: TP / (TP + FN)\n- F1 Score: 2 × (P × R) / (P + R)",
    tags: ["machine-learning", "python", "tensorflow", "deep-learning", "ai"],
    pages: 856,
    readingTimeMinutes: 1440,
    isFree: false,
    priceCredits: 200,
    rating: "4.94",
    reviewCount: 4123,
    downloads: 28750,
  },
  {
    title: "UPSC General Studies Paper 1 — Complete Strategy Guide",
    author: "M. Laxmikanth",
    category: "upsc",
    coverUrl: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=300&h=420&fit=crop",
    shortDesc: "Master GS Paper 1 — History, Geography, Society with previous year analysis.",
    description: "Comprehensive coverage of UPSC GS Paper 1 syllabus including Indian History, World History, Indian and World Geography, Indian Society, and Culture. Includes previous year question analysis, answer writing strategies, and current affairs integration. A must-have for UPSC aspirants aiming for top ranks.",
    aiSummary: "UPSC GS Paper 1 strategy: 1) Indian History — Ancient (Vedic, Maurya, Gupta), Medieval (Delhi Sultanate, Mughals), Modern (Freedom Struggle, key leaders). 2) Geography — Physical geography, climate, rivers, natural resources, human geography, world geography. 3) Society — Social empowerment, communalism, regionalism, secularism. 4) Answer writing: Use UPSC language, structure with intro-body-conclusion, cite recent examples, 150-250 words per answer. Start with NCERT books then standard references.",
    contentPreview: "Unit 1: Indian History — Modern India\n\n1857 Revolt — The First War of Independence\n\nCauses:\n1. Political — Doctrine of Lapse (Lord Dalhousie), annexation of Awadh\n2. Economic — Drain of wealth, destruction of Indian industries\n3. Military — General Service Enlistment Act, Enfield rifle cartridge\n4. Religious — Fear of forced conversion\n\nKey Leaders: Mangal Pandey, Rani Laxmibai, Tantia Tope, Bahadur Shah Zafar\n\nConsequences:\n• End of East India Company rule\n• Crown took direct control (Queen's Proclamation 1858)\n• Secretary of State for India created\n• Army reorganized — reduced Indian soldiers",
    tags: ["upsc", "general-studies", "history", "geography", "ias"],
    pages: 680,
    readingTimeMinutes: 1200,
    isFree: true,
    priceCredits: 0,
    rating: "4.83",
    reviewCount: 6741,
    downloads: 41200,
  },
  {
    title: "System Design Interview — An Insider's Guide",
    author: "Alex Xu",
    category: "engineering",
    coverUrl: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=300&h=420&fit=crop",
    shortDesc: "Design scalable systems like URL shortener, Twitter, YouTube, and more.",
    description: "Learn how to design large-scale distributed systems. Each chapter walks through a real-world system design problem with a step-by-step framework. Topics include load balancing, caching, database design, microservices, message queues, CDN, and more. Perfect for software engineers preparing for FAANG interviews.",
    aiSummary: "System design framework: 1) Clarify requirements — functional and non-functional (scale, availability, latency). 2) Estimate scale — QPS, storage, bandwidth. 3) High-level design — components, APIs, data flow. 4) Deep dive — database schema, caching strategy, sharding. Key concepts: Load balancer (distribute traffic), Cache (Redis for fast reads), CDN (static assets), Message queue (Kafka for async processing), Database (SQL vs NoSQL choice), Sharding (horizontal scaling). Always design for failure — replication, failover, rate limiting.",
    contentPreview: "Chapter 6: Design a URL Shortener\n\nStep 1: Requirements\n- Functional: Shorten URL, redirect to original\n- Non-functional: 100M URLs/day, high availability, low latency\n\nStep 2: Capacity\n- Write: 100M/day = 1,160 URLs/sec\n- Read: 10:1 ratio = 11,600 redirects/sec\n- Storage: 100M × 365 × 10 years × 100 bytes = 365GB\n\nStep 3: API Design\nPOST /api/v1/data/shorten → { shortUrl: 'http://short.ly/abc123' }\nGET /api/v1/{shortUrl} → 301 redirect\n\nStep 4: Database\nURL table: id | shortCode | longUrl | createdAt | userId",
    tags: ["system-design", "distributed-systems", "interview", "engineering", "faang"],
    pages: 352,
    readingTimeMinutes: 540,
    isFree: false,
    priceCredits: 150,
    rating: "4.91",
    reviewCount: 3892,
    downloads: 22100,
  },
  {
    title: "Anatomy & Physiology for Medical Students",
    author: "Gray's Anatomy — Adapted",
    category: "medical",
    coverUrl: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=300&h=420&fit=crop",
    shortDesc: "Complete human anatomy with clinical correlations for MBBS and NEET.",
    description: "A comprehensive anatomy and physiology guide designed for medical students. Covers all body systems including musculoskeletal, cardiovascular, respiratory, digestive, nervous, endocrine, and reproductive systems. Each chapter includes clinical correlations, mnemonics, and high-yield NEET/MBBS exam points.",
    aiSummary: "Key anatomy systems: 1) Cardiovascular — heart chambers, valves, coronary arteries, conduction system (SA node → AV node → Bundle of His → Purkinje). 2) Respiratory — lung lobes, bronchi, gas exchange at alveoli. 3) Nervous — CNS (brain, spinal cord) and PNS, autonomic NS (sympathetic 'fight-or-flight', parasympathetic 'rest-digest'). 4) Digestive — GI tract from mouth to rectum, liver, pancreas enzymes. High-yield for NEET: Know clinical correlations, common surgeries, nerve injuries and their effects.",
    contentPreview: "Chapter 8: The Heart\n\nStructure:\n- 4 chambers: Right atrium, Right ventricle, Left atrium, Left ventricle\n- Right side: Deoxygenated blood → Pulmonary circulation\n- Left side: Oxygenated blood → Systemic circulation\n\nValves:\n• Tricuspid (Right AV valve) — 3 cusps\n• Pulmonary valve — separates RV from pulmonary trunk\n• Mitral/Bicuspid (Left AV valve) — 2 cusps\n• Aortic valve — separates LV from aorta\n\nMnemonic: 'Tri before Bi' — right side has tricuspid, left has bicuspid\n\nCoronary arteries:\n- LAD (Left Anterior Descending) — supplies anterior LV, 'widow maker'\n- RCA — supplies SA node, AV node, posterior heart",
    tags: ["anatomy", "physiology", "mbbs", "neet", "medical"],
    pages: 924,
    readingTimeMinutes: 1800,
    isFree: true,
    priceCredits: 0,
    rating: "4.77",
    reviewCount: 4521,
    downloads: 31800,
  },
  {
    title: "The Lean Startup — Build, Measure, Learn",
    author: "Eric Ries",
    category: "business",
    coverUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=420&fit=crop",
    shortDesc: "How modern entrepreneurs use continuous innovation to build successful businesses.",
    description: "The Lean Startup introduces a scientific approach to building and managing startups. Learn the Build-Measure-Learn feedback loop, how to test hypotheses with minimum viable products (MVPs), pivot or persevere decisions, innovation accounting, and how to avoid building products nobody wants.",
    aiSummary: "Lean Startup core principles: 1) Build-Measure-Learn cycle — build MVP, measure user behavior, learn and iterate. 2) Validated learning — test hypotheses with real customers before building. 3) MVP (Minimum Viable Product) — smallest version that lets you learn. 4) Pivot or Persevere — when experiments fail, change strategy (pivot), don't abandon vision. 5) Innovation accounting — use actionable metrics, not vanity metrics (page views don't tell you if users value your product). 6) Continuous deployment — ship frequently, learn faster. The goal is to find product-market fit before running out of resources.",
    contentPreview: "Part II: Steer\n\nThe Leap of Faith\n\nEvery business plan begins with assumptions — leap of faith assumptions that the product will be valuable. The question is: how quickly can we test these assumptions?\n\nTuneIn Radio's founders built an MVP in weeks — a simple music streaming app with minimal features. They didn't build the perfect product; they built the smallest thing that would let customers tell them if the idea was worth pursuing.\n\nValue hypothesis: Does the product deliver value to customers when they use it?\nGrowth hypothesis: How will new customers discover the product?\n\nKey insight: Success is not delivering features. Success is learning which features to build.",
    tags: ["entrepreneurship", "startup", "business", "product-management", "mvp"],
    pages: 336,
    readingTimeMinutes: 360,
    isFree: false,
    priceCredits: 80,
    rating: "4.68",
    reviewCount: 7812,
    downloads: 44300,
  },
  {
    title: "Atomic Habits — Build Systems That Last",
    author: "James Clear",
    category: "productivity",
    coverUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&h=420&fit=crop",
    shortDesc: "Tiny changes, remarkable results. Build good habits and break bad ones.",
    description: "Atomic Habits reveals the science behind how habits form and provides a practical framework for improving every day. Learn the four laws of behavior change, how to design your environment for success, why identity-based habits stick, and how 1% improvements compound into extraordinary results over time.",
    aiSummary: "Atomic Habits framework: 1) Make it obvious — design your environment, use habit stacking. 2) Make it attractive — temptation bundling, join a culture where your desired behavior is normal. 3) Make it easy — reduce friction, two-minute rule (start with 2 minutes). 4) Make it satisfying — immediate reward, habit tracking. For bad habits, invert each law. The 1% better rule: improving 1% daily = 37× better in a year. Identity-based habits: 'I am a reader' vs 'I want to read more'. Systems beat goals — focus on the process, not the outcome.",
    contentPreview: "Chapter 3: How to Build Better Habits in 4 Simple Steps\n\nThe Habit Loop:\nCue → Craving → Response → Reward\n\nExample — Study habit:\n• Cue: Alarm at 7 AM + books on desk (visible)\n• Craving: Want to feel accomplished and informed\n• Response: Open textbook, read for 25 minutes\n• Reward: Check off study log, 5-minute break\n\nHabit Stacking formula:\n'After [CURRENT HABIT], I will [NEW HABIT].'\n\nExample: 'After I pour my morning coffee, I will open my textbook.'\n\nThe Two-Minute Rule:\nScale habits down until they take two minutes or less. 'Read before bed' → 'Read one page'. Start the habit, then expand.",
    tags: ["habits", "productivity", "self-improvement", "psychology", "mindset"],
    pages: 320,
    readingTimeMinutes: 360,
    isFree: false,
    priceCredits: 80,
    rating: "4.95",
    reviewCount: 12435,
    downloads: 67800,
  },
  {
    title: "React.js Complete Guide — Hooks, Context & Advanced Patterns",
    author: "Maximilian Schwarzmüller",
    category: "coding",
    coverUrl: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=300&h=420&fit=crop",
    shortDesc: "Build modern React applications with hooks, context, Redux, and TypeScript.",
    description: "A comprehensive guide to modern React development. Start from fundamentals and progress to advanced topics including functional components, hooks (useState, useEffect, useCallback, useMemo, useRef), custom hooks, React Context, Redux Toolkit, React Router, performance optimization, and TypeScript integration.",
    aiSummary: "React mastery path: 1) Components — functional components are standard (hooks replaced class components). 2) Core hooks: useState (local state), useEffect (side effects/API calls), useContext (global state), useCallback/useMemo (performance optimization), useRef (DOM access). 3) State management: Local state → Context API → Redux Toolkit (for complex apps). 4) Performance: React.memo (prevent rerenders), lazy loading, code splitting. 5) TypeScript with React: type Props, use generics, typed events. Key principle: Lift state up when siblings need to share it.",
    contentPreview: "Chapter 5: React Hooks Deep Dive\n\nuseEffect — The Side Effect Hook\n\n```tsx\nfunction UserProfile({ userId }: { userId: string }) {\n  const [user, setUser] = useState<User | null>(null);\n  const [loading, setLoading] = useState(true);\n\n  useEffect(() => {\n    let cancelled = false;\n    \n    async function fetchUser() {\n      const data = await api.getUser(userId);\n      if (!cancelled) {\n        setUser(data);\n        setLoading(false);\n      }\n    }\n    \n    fetchUser();\n    return () => { cancelled = true; }; // Cleanup\n  }, [userId]); // Re-run when userId changes\n  \n  if (loading) return <Spinner />;\n  return <div>{user?.name}</div>;\n}\n```",
    tags: ["react", "javascript", "typescript", "hooks", "frontend"],
    pages: 628,
    readingTimeMinutes: 900,
    isFree: false,
    priceCredits: 150,
    rating: "4.88",
    reviewCount: 3241,
    downloads: 19800,
  },
  {
    title: "Operating Systems — Three Easy Pieces",
    author: "Remzi Arpaci-Dusseau",
    category: "engineering",
    coverUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=300&h=420&fit=crop",
    shortDesc: "Virtualization, Concurrency, and Persistence — the three pillars of OS design.",
    description: "A free and comprehensive textbook on operating systems covering the three core topics: virtualization (CPU and memory), concurrency (threads, locks, semaphores), and persistence (file systems, I/O). Written in an approachable style with dialogue between students and instructors, making complex OS concepts accessible.",
    aiSummary: "OS fundamentals: 1) Virtualization — CPU virtualization through context switching (illusion of multiple CPUs), memory virtualization through paging (each process has its own address space). 2) Concurrency — threads share address space, race conditions occur with shared data, solved with locks (mutex), semaphores, condition variables. 3) Persistence — storage organized in file systems (inodes track file metadata), journaling prevents corruption. Key concepts: Process vs Thread, Deadlock (circular wait), Virtual memory (TLB, page tables), File system (ext4, NTFS structure).",
    contentPreview: "Chapter 26: Concurrency: An Introduction\n\nA thread is like a separate process, but shares the same address space. This sharing creates problems.\n\nRace Condition:\n```c\n// Global counter — two threads increment it\nint counter = 0;\n\nvoid *increment(void *arg) {\n    for (int i = 0; i < 1e7; i++)\n        counter++;  // NOT ATOMIC — 3 instructions!\n    return NULL;\n}\n// Expected: 20,000,000. Actual: random < 20M\n```\n\nSolution — Mutex lock:\n```c\npthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER;\npthread_mutex_lock(&lock);\ncounter++;\npthread_mutex_unlock(&lock);\n```",
    tags: ["operating-systems", "concurrency", "cs", "engineering", "systems"],
    pages: 694,
    readingTimeMinutes: 1100,
    isFree: true,
    priceCredits: 0,
    rating: "4.82",
    reviewCount: 2891,
    downloads: 15400,
  },
  {
    title: "Organic Chemistry for JEE Advanced",
    author: "M.S. Chouhan",
    category: "school",
    coverUrl: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=300&h=420&fit=crop",
    shortDesc: "Master organic chemistry with mechanisms, reactions, and JEE-level problems.",
    description: "A complete organic chemistry resource for JEE Advanced preparation. Covers all major topics: GOC (General Organic Chemistry), IUPAC nomenclature, isomerism, reaction mechanisms (SN1, SN2, E1, E2, addition, elimination, substitution), named reactions, and spectral analysis. Includes 1500+ solved JEE problems.",
    aiSummary: "Organic Chemistry strategy: 1) GOC first — electronegativity, inductive effect, resonance, hyperconjugation determine reactivity. 2) Reaction mechanisms: SN1 (stable carbocation, racemization), SN2 (backside attack, inversion), E1/E2 (elimination). 3) Named reactions to memorize: Aldol condensation, Cannizzaro, Grignard, Wolff-Kishner, Clemmensen, Baeyer-Villiger. 4) Functional group identification: IR and NMR spectroscopy. JEE tip: Focus on predicting major products — identify nucleophile/electrophile, apply mechanism, predict stereochemistry.",
    contentPreview: "Chapter 4: Nucleophilic Substitution Reactions\n\nSN2 (Bimolecular Nucleophilic Substitution)\n\nKey features:\n• One-step concerted mechanism\n• Backside attack by nucleophile\n• Inversion of configuration (Walden inversion)\n• Rate = k[substrate][nucleophile]\n• Favored: Primary > Secondary > Tertiary alkyl halides\n• Best solvents: Polar aprotic (DMSO, acetone)\n\nExample:\n(R)-2-bromobutane + OH⁻ → (S)-2-butanol\n\nRemember: SN2 = 'SN-inVersion' — configuration inverts\n\nOrder of leaving groups: I⁻ > Br⁻ > Cl⁻ > F⁻\nOrder of nucleophilicity: RS⁻ > I⁻ > CN⁻ > Br⁻ > Cl⁻ > F⁻",
    tags: ["chemistry", "organic", "jee", "class-11", "class-12"],
    pages: 580,
    readingTimeMinutes: 1050,
    isFree: true,
    priceCredits: 0,
    rating: "4.81",
    reviewCount: 5621,
    downloads: 38700,
  },
];

async function seedLibrary() {
  console.log("Seeding library books...");
  await db.delete(libraryBooksTable);
  for (const book of books) {
    await db.insert(libraryBooksTable).values(book as typeof libraryBooksTable.$inferInsert);
  }
  console.log(`✓ Inserted ${books.length} library books`);
}

seedLibrary()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
