import { db } from "@workspace/db";
import { marketplaceItemsTable, marketplacePurchasesTable } from "@workspace/db/schema";

const items = [
  {
    title: "DSA Interview Cheatsheet — 200 Problems Solved",
    creatorName: "Rahul Gupta",
    creatorAvatar: "https://i.pravatar.cc/150?img=12",
    category: "notes",
    priceCredits: 150,
    isFree: false,
    rating: "4.92",
    reviewCount: 834,
    downloads: 5230,
    description: "Complete DSA cheat sheet with 200 solved problems across Arrays, Strings, Trees, Graphs, DP, and more. Includes time/space complexity for every solution, common patterns, and interview tips from a Google SWE.",
    previewUrl: null,
    tags: ["dsa", "interview", "coding", "arrays", "trees"],
    fileType: "pdf",
    isFeatured: true,
  },
  {
    title: "React + TypeScript Admin Dashboard Template",
    creatorName: "Priya Sharma",
    creatorAvatar: "https://i.pravatar.cc/150?img=47",
    category: "templates",
    priceCredits: 250,
    isFree: false,
    rating: "4.88",
    reviewCount: 512,
    downloads: 3890,
    description: "Production-ready React + TypeScript admin dashboard with Tailwind CSS. Includes 15+ pages: Analytics, Users, Orders, Settings, Auth. Dark/light mode, responsive design, Recharts integration, and full TypeScript types.",
    previewUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop",
    tags: ["react", "typescript", "dashboard", "tailwind", "template"],
    fileType: "zip",
    isFeatured: true,
  },
  {
    title: "UPSC Polity Complete Notes — M. Laxmikanth Summary",
    creatorName: "Anjali Verma",
    creatorAvatar: "https://i.pravatar.cc/150?img=23",
    category: "notes",
    priceCredits: 80,
    isFree: false,
    rating: "4.85",
    reviewCount: 2341,
    downloads: 14200,
    description: "Complete Indian Polity notes based on M. Laxmikanth covering Constitution, Fundamental Rights, DPSP, Parliament, President, Governor, Judiciary, and more. Includes mind maps, previous year questions, and answer writing templates.",
    previewUrl: null,
    tags: ["upsc", "polity", "constitution", "ias", "notes"],
    fileType: "pdf",
    isFeatured: false,
  },
  {
    title: "Full-Stack MERN Blog Platform — Source Code",
    creatorName: "Arjun Mehta",
    creatorAvatar: "https://i.pravatar.cc/150?img=8",
    category: "source-code",
    priceCredits: 300,
    isFree: false,
    rating: "4.76",
    reviewCount: 287,
    downloads: 1890,
    description: "Complete MERN stack blog platform with authentication, rich text editor, categories, tags, comments, likes, and admin panel. Built with MongoDB, Express, React, Node.js. Includes deployment guide for Vercel + Railway.",
    previewUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop",
    tags: ["mern", "nodejs", "react", "mongodb", "fullstack"],
    fileType: "zip",
    isFeatured: true,
  },
  {
    title: "Physics Formula Sheets — Class 11 & 12 Complete",
    creatorName: "Dr. Kavitha Rao",
    creatorAvatar: "https://i.pravatar.cc/150?img=56",
    category: "notes",
    priceCredits: 0,
    isFree: true,
    rating: "4.79",
    reviewCount: 4521,
    downloads: 28900,
    description: "All important physics formulas for Class 11 and 12 — Mechanics, Thermodynamics, Electromagnetism, Optics, Modern Physics. Beautifully formatted with derivation hints and SI units.",
    previewUrl: null,
    tags: ["physics", "class-11", "class-12", "formulas", "jee"],
    fileType: "pdf",
    isFeatured: false,
  },
  {
    title: "Hacker Neon IDE Theme Pack",
    creatorName: "TechCreator_Dev",
    creatorAvatar: "https://i.pravatar.cc/150?img=33",
    category: "theme-packs",
    priceCredits: 60,
    isFree: false,
    rating: "4.71",
    reviewCount: 1230,
    downloads: 7800,
    description: "5 premium dark IDE themes inspired by cyberpunk aesthetics. Includes Hacker Neon, Cyber Grid, Plasma Dark, Ghost Purple, and Matrix Green. Compatible with VS Code, Vim, and EduConnect CodeLab.",
    previewUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&h=400&fit=crop",
    tags: ["themes", "vscode", "dark-mode", "ide", "design"],
    fileType: "zip",
    isFeatured: false,
  },
  {
    title: "Machine Learning Roadmap 2025 — Complete Study Bundle",
    creatorName: "Siddharth AI",
    creatorAvatar: "https://i.pravatar.cc/150?img=15",
    category: "study-bundles",
    priceCredits: 400,
    isFree: false,
    rating: "4.95",
    reviewCount: 678,
    downloads: 4100,
    description: "Complete ML learning bundle: roadmap PDF, 50+ Jupyter notebooks, dataset collection, project ideas list, resource links, and community Discord access. Takes you from zero to job-ready ML engineer in 6 months.",
    previewUrl: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&h=400&fit=crop",
    tags: ["machine-learning", "python", "tensorflow", "roadmap", "ai"],
    fileType: "zip",
    isFeatured: true,
  },
  {
    title: "Figma UI Kit — 500+ Education App Components",
    creatorName: "Neha Designs",
    creatorAvatar: "https://i.pravatar.cc/150?img=44",
    category: "ui-kits",
    priceCredits: 200,
    isFree: false,
    rating: "4.83",
    reviewCount: 445,
    downloads: 2890,
    description: "500+ Figma components designed specifically for educational apps. Includes course cards, progress trackers, quiz interfaces, leaderboards, coding IDE mockups, and 20+ complete screen designs. Light and dark variants.",
    previewUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=400&fit=crop",
    tags: ["figma", "ui-kit", "design", "components", "education"],
    fileType: "zip",
    isFeatured: false,
  },
  {
    title: "Python REST API Starter — FastAPI + PostgreSQL",
    creatorName: "Kiran Backend",
    creatorAvatar: "https://i.pravatar.cc/150?img=6",
    category: "source-code",
    priceCredits: 180,
    isFree: false,
    rating: "4.80",
    reviewCount: 312,
    downloads: 2100,
    description: "Production-ready FastAPI starter with PostgreSQL, SQLAlchemy, Alembic migrations, JWT authentication, CORS, rate limiting, Redis caching, Docker setup, and comprehensive test suite. Perfect foundation for any backend project.",
    previewUrl: null,
    tags: ["python", "fastapi", "postgresql", "jwt", "backend"],
    fileType: "zip",
    isFeatured: false,
  },
  {
    title: "JEE Mathematics — Complete Formula Book",
    creatorName: "MathGuru JEE",
    creatorAvatar: "https://i.pravatar.cc/150?img=67",
    category: "notes",
    priceCredits: 0,
    isFree: true,
    rating: "4.88",
    reviewCount: 6820,
    downloads: 41200,
    description: "All JEE Mathematics formulas in one place — Algebra, Trigonometry, Calculus, Coordinate Geometry, Vectors, and 3D Geometry. Includes important theorems, shortcuts, and previous year pattern analysis.",
    previewUrl: null,
    tags: ["jee", "mathematics", "calculus", "algebra", "formulas"],
    fileType: "pdf",
    isFeatured: false,
  },
  {
    title: "Minimal Light — Premium App Theme Pack",
    creatorName: "DesignStudio_IX",
    creatorAvatar: "https://i.pravatar.cc/150?img=29",
    category: "theme-packs",
    priceCredits: 40,
    isFree: false,
    rating: "4.65",
    reviewCount: 892,
    downloads: 5600,
    description: "4 clean minimal light themes for productivity apps. Includes Paper White, Arctic Blue, Sand Beige, and Forest Green. Reduces eye strain and keeps your focus on the content.",
    previewUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop",
    tags: ["themes", "minimal", "light-mode", "productivity", "design"],
    fileType: "zip",
    isFeatured: false,
  },
  {
    title: "Competitive Programming Starter Pack",
    creatorName: "CP_Champion",
    creatorAvatar: "https://i.pravatar.cc/150?img=18",
    category: "study-bundles",
    priceCredits: 200,
    isFree: false,
    rating: "4.90",
    reviewCount: 534,
    downloads: 3400,
    description: "Everything to get started in competitive programming: template code (C++/Python), 500+ handpicked Codeforces/LeetCode problems by topic, editorial collection, ICPC preparation guide, and weekly problem sets.",
    previewUrl: null,
    tags: ["competitive-programming", "cpp", "algorithms", "codeforces", "icpc"],
    fileType: "zip",
    isFeatured: true,
  },
  {
    title: "OpenAI API Integration Templates — 10 Use Cases",
    creatorName: "AI_Builder_Labs",
    creatorAvatar: "https://i.pravatar.cc/150?img=51",
    category: "source-code",
    priceCredits: 220,
    isFree: false,
    rating: "4.77",
    reviewCount: 198,
    downloads: 1450,
    description: "10 ready-to-use OpenAI API integration templates: chatbot, code review bot, document summarizer, quiz generator, SQL query generator, email assistant, image analyzer, flashcard creator, tutor bot, and interview prep bot.",
    previewUrl: null,
    tags: ["openai", "api", "chatgpt", "python", "nodejs"],
    fileType: "zip",
    isFeatured: false,
  },
];

async function seedMarketplace() {
  console.log("Seeding marketplace items...");
  await db.delete(marketplacePurchasesTable);
  await db.delete(marketplaceItemsTable);
  for (const item of items) {
    await db.insert(marketplaceItemsTable).values(item as typeof marketplaceItemsTable.$inferInsert);
  }
  console.log(`✓ Inserted ${items.length} marketplace items`);
}

seedMarketplace()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
